<a href="https://colab.research.google.com/github/Luisrodriguez19/heart_failure_clinical_records_dataset.csv/blob/main/IC_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTAMOS LA BASE DE DATOS DESDE GIT HUB**


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
url='https://raw.githubusercontent.com/Luisrodriguez19/heart_failure_clinical_records_dataset.csv/main/BD.csv'
df=pd.read_csv(url)
print (df.head(12))
"""
Si hay valores vacios los remplazamos"""
dataset = df.replace(np.nan,"0")


     age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0   75.0        0                       582  ...        0     4            1
1   55.0        0                      7861  ...        0     6            1
2   65.0        0                       146  ...        1     7            1
3   50.0        1                       111  ...        0     7            1
4   65.0        1                       160  ...        0     8            1
5   90.0        1                        47  ...        1     8            1
6   75.0        1                       246  ...        0    10            1
7   60.0        1                       315  ...        1    10            1
8   65.0        0                       157  ...        0    10            1
9   80.0        1                       123  ...        1    10            1
10  75.0        1                        81  ...        1    10            1
11  62.0        0                       231  ...        1    10            1

# **Convertimos el dataframe en un arreglo**

In [ ]:
dataset = df.values
print (dataset.shape)

(299, 13)


In [ ]:
#Definimos las entradas a la red neuronal"""
#X=dataset[['anaemia','creatinine_phosphokinase','diabetes','ejection_fraction','high_blood_pressure','platelets','serum_creatinine','serum_sodium','sex','smoking','time']]
"""#Variable dependiente"""
X = dataset[:, 0:12]
Y = dataset[:, 12]

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale



array([[0.63636364, 0.        , 0.07131921, ..., 1.        , 0.        ,
        0.        ],
       [0.27272727, 0.        , 1.        , ..., 1.        , 0.        ,
        0.00711744],
       [0.45454545, 0.        , 0.01569278, ..., 1.        , 1.        ,
        0.01067616],
       ...,
       [0.09090909, 0.        , 0.25988773, ..., 0.        , 0.        ,
        0.97508897],
       [0.09090909, 0.        , 0.30492473, ..., 1.        , 1.        ,
        0.98220641],
       [0.18181818, 0.        , 0.02207196, ..., 1.        , 1.        ,
        1.        ]])

In [ ]:
import plotly.express as px
import numpy as np
x = np.arange(len(X_scale))
y = X_scale[:,2]
fig = px.line(x=x, y=y,title='Distribución')
fig.show()

## **Datos para el entrenamiento**

In [ ]:
 import numpy as np
 from sklearn.model_selection import train_test_split
 X, y = np.arange(20).reshape((10,2)), np.arange(10)
 print("X: ", len(X))
 print(X)
 print("y: ",len(y))
 print(y)

X:  10
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
y:  10
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
X_train, X_val_test, y_train, y_val_test = train_test_split(X,y, test_size=0.3, random_state=42)
#random
print("X_train:",len(X_train))
print(X_train)
print("X_val_test:",len(X_val_test))
print(X_val_test)
print("y_train:",len(y_train))
print(y_train)
print("y_val_test:",len(y_val_test))
print(y_val_test)


X_train: 7
[[ 0  1]
 [14 15]
 [ 4  5]
 [18 19]
 [ 8  9]
 [ 6  7]
 [12 13]]
X_val_test: 3
[[16 17]
 [ 2  3]
 [10 11]]
y_train: 7
[0 7 2 9 4 3 6]
y_val_test: 3
[8 1 5]


In [ ]:
X_val, X_test, y_val, y_test = train_test_split(X_val_test,y_val_test, test_size=0.5,random_state=42)
#random
print("X_val:",len(X_val))
print(X_val)
print("X_val_test:",len(X_test))
print(X_test)
print("y_val:",len(y_val))
print(y_val)
print("y_val_test:",len(y_test))
print(y_test)

X_val: 1
[[10 11]]
X_val_test: 2
[[16 17]
 [ 2  3]]
y_val: 1
[5]
y_val_test: 2
[8 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)
print(X_train.shape, X_val.shape, X_test.shape, y_train.shape, y_val.shape, y_test.shape)

(209, 12) (45, 12) (45, 12) (7,) (1,) (2,)


## **Función de activación calcula la información de salida  de una neurona**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential([
                    #dos capas encondidas con 32 neuronas
    Dense(32, activation='relu',input_shape=(12,)),
    Dense(32, activation='relu'),
    #resultado
    Dense(1, activation='sigmoid'),
])

## **Optimización del modelo, función de perdida: loss, función de exactitud: accuracy**

In [ ]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
hist = model.fit(X_train, Y_train,
                 batch_size=32, epochs=100,
                 validation_data=(X_val, Y_val))

Epoch 1/100
7/7 [==============================] - 0s 24ms/step - loss: 0.6338 - accuracy: 0.6842 - val_loss: 0.6406 - val_accuracy: 0.6667
Epoch 2/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6318 - accuracy: 0.6842 - val_loss: 0.6389 - val_accuracy: 0.6667
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6299 - accuracy: 0.6842 - val_loss: 0.6375 - val_accuracy: 0.6667
Epoch 4/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6283 - accuracy: 0.6842 - val_loss: 0.6358 - val_accuracy: 0.6667
Epoch 5/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6263 - accuracy: 0.6842 - val_loss: 0.6345 - val_accuracy: 0.6667
Epoch 6/100
7/7 [==============================] - 0s 3ms/step - loss: 0.6249 - accuracy: 0.6842 - val_loss: 0.6332 - val_accuracy: 0.6667
Epoch 7/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6234 - accuracy: 0.6842 - val_loss: 0.6320 - val_accuracy: 0.6667
Epoch 8/100
7/7 [=========

In [ ]:
model.evaluate(X_test, Y_test)[1]

2/2 [==============================] - 0s 3ms/step - loss: 0.5751 - accuracy: 0.6667


0.6666666865348816